version: "3.9"

services:
  backend:
    build:
      context: ./Backend/SupportApi
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./Backend/SupportApi/support.db:/app/support.db

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend